inherit_gem:
  rubocop-github: config/default.yml

require:
  - ./lib/rubocop/cop/graphql/heredoc

AllCops:
  TargetRubyVersion: 2.3

GraphQL/Heredoc:
  Enabled: true

Naming/FileName:
  Exclude:
    - lib/graphql-client.rb